spring.application.name=city-explorer
spring.datasource.url=jdbc:h2:file:./data/aurevia-db-v2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
spring.h2.console.enabled=true
server.error.include-message=always
server.error.whitelabel.enabled=false
server.forward-headers-strategy=framework
server.port=${PORT:8080}
logging.level.com.aurevia.cityexplorer.config.RequestLoggingFilter=INFO
logging.level.com.aurevia.cityexplorer.config.SecurityConfig=INFO
logging.level.org.springframework.security.web.access=DEBUG
