spring.application.name=city-explorer
spring.datasource.url=jdbc:h2:file:./data/aurevia-db-v2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
spring.h2.console.enabled=true
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
aurevia.contact.recipient-email=sayamaarora@gmail.com
server.error.include-message=always
server.error.whitelabel.enabled=false
server.forward-headers-strategy=framework
server.port=${PORT:8080}
logging.level.com.aurevia.cityexplorer.config.RequestLoggingFilter=INFO
logging.level.com.aurevia.cityexplorer.config.SecurityConfig=INFO
logging.level.org.springframework.security.web.access=DEBUG

spring.h2.console.settings.web-allow-others=true
